from __future__ import annotations

# Top 50 MVP plants ranked by ressarcible COFF energy in NE, using CNF/REL
# with origin different from LOC and the MVP franchise approximation.
TOP_50_USINA_IDS: tuple[str, ...] = ('CJU_BAFFUT',
 'CJU_RNSDMC',
 'CJU_PI5FGID',
 'CJU_RNMEND',
 'CJU_BASSD',
 'CJU_PEBELM',
 'CJU_PIFMRG',
 'CJU_RNASO',
 'CJU_CEUFAL',
 'CJU_PBSLDF5',
 'CJU_BABRD',
 'CJU_PBRAL',
 'CJU_PINVO',
 'CJU_RNMVS',
 'CJU_PIFSBA',
 'CJU_CELAV',
 'CJU_PECIR',
 'CJU_PISJP',
 'CJU_CEAB2',
 'CJU_PIRG3',
 'CJU_CEPTN',
 'CJU_BATBV',
 'CJU_PBLZA',
 'CJU_BAJZS2',
 'CJU_PEBRI',
 'CJU_CECAL',
 'CJU_CEFSEM',
 'CJU_CEMTD',
 'CJU_BAJZS',
 'CJU_PISGO',
 'CJU_PI5FRGV',
 'CJU_CESDF',
 'CJU_BAHZT',
 'CJU_BASSB',
 'CJU_BA4FJZD',
 'CJU_RNSPC',
 'CJU_RNFLO',
 'CJU_PESPP',
 'CJU_CELINS',
 'CJU_BALAP',
 'CJU_BABJU',
 'CJU_BASPD',
 'RNFVAE',
 'PISDP1',
 'CJU_BABJL',
 'CEUPTM',
 'CJU_BASSDB',
 'CJU_PISGOA',
 'CJU_PEMRRC',
 'CJU_BA3FIRE')

# Static metadata snapshot for the selection screen. Keeping this list in-process
# avoids scanning large raw public tables just to render the plant picker. Detail
# and metric endpoints still query the database for the selected plant.
TOP_50_USINA_ROWS: tuple[dict[str, object], ...] = ({'usina_id': 'CJU_BAFFUT',
  'nome': 'Conj. Futura',
  'fonte': 'Solar',
  'potencia_mw': 692.4456,
  'submercado': 'NE',
  'latitude': -9.660782,
  'longitude': -40.686021,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_RNSDMC',
  'nome': 'Conj. Serra do Mel C',
  'fonte': 'Solar',
  'potencia_mw': 433.05328,
  'submercado': 'NE',
  'latitude': -5.130153553436521,
  'longitude': -37.049659026333,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PI5FGID',
  'nome': 'Conj. Gilbués II 500 kV',
  'fonte': 'Solar',
  'potencia_mw': 790.88533339,
  'submercado': 'NE',
  'latitude': -10.103855,
  'longitude': -45.282352,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_RNMEND',
  'nome': 'Conj. Açú III 230 kV',
  'fonte': 'Solar',
  'potencia_mw': 452.412,
  'submercado': 'NE',
  'latitude': -5.615819,
  'longitude': -37.035712,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BASSD',
  'nome': 'Conj. Sol do Sertão',
  'fonte': 'Solar',
  'potencia_mw': 415.03,
  'submercado': 'NE',
  'latitude': -12.23913,
  'longitude': -42.610434,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PEBELM',
  'nome': 'Conj. Belmonte',
  'fonte': 'Solar',
  'potencia_mw': 455.001,
  'submercado': 'NE',
  'latitude': -7.870061,
  'longitude': -38.83471,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PIFMRG',
  'nome': 'Conj. Marangatu',
  'fonte': 'Solar',
  'potencia_mw': 360.0,
  'submercado': 'NE',
  'latitude': -4.082201,
  'longitude': -41.273043,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_RNASO',
  'nome': 'Conj. Assu Sol',
  'fonte': 'Solar',
  'potencia_mw': 752.65144,
  'submercado': 'NE',
  'latitude': -5.59,
  'longitude': -37.0346,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CEUFAL',
  'nome': 'Conj. Alex',
  'fonte': 'Solar',
  'potencia_mw': 278.397,
  'submercado': 'NE',
  'latitude': -5.269671,
  'longitude': -37.967945,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PBSLDF5',
  'nome': 'Conj. Santa Luzia II 500 kV',
  'fonte': 'Solar',
  'potencia_mw': 250.0,
  'submercado': 'NE',
  'latitude': -6.9127055,
  'longitude': -36.9775231,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BABRD',
  'nome': 'Conj. Barreiras II 500 kV',
  'fonte': 'Solar',
  'potencia_mw': 350.0,
  'submercado': 'NE',
  'latitude': -12.17164056223678,
  'longitude': -44.80828338390143,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PBRAL',
  'nome': 'Conj. Rio Alto',
  'fonte': 'Solar',
  'potencia_mw': 216.0,
  'submercado': 'NE',
  'latitude': -6.9661,
  'longitude': -37.9892,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PINVO',
  'nome': 'Conj. Nova Olinda',
  'fonte': 'Solar',
  'potencia_mw': 210.0,
  'submercado': 'NE',
  'latitude': -8.194181,
  'longitude': -42.556878,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_RNMVS',
  'nome': 'Conj. Monte Verde Solar',
  'fonte': 'Solar',
  'potencia_mw': 212.38226,
  'submercado': 'NE',
  'latitude': None,
  'longitude': None,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PIFSBA',
  'nome': 'Conj. São Basílio',
  'fonte': 'Solar',
  'potencia_mw': 213.134,
  'submercado': 'NE',
  'latitude': -7.396478,
  'longitude': -40.579867,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CELAV',
  'nome': 'Conj. Lavras',
  'fonte': 'Solar',
  'potencia_mw': 201.0,
  'submercado': 'NE',
  'latitude': -3.791728,
  'longitude': -38.932812,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PECIR',
  'nome': 'Conj. Ciranda',
  'fonte': 'Solar',
  'potencia_mw': 244.5,
  'submercado': 'NE',
  'latitude': -7.963652,
  'longitude': -38.627376,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PISJP',
  'nome': 'Conj. SJP',
  'fonte': 'Solar',
  'potencia_mw': 186.05,
  'submercado': 'NE',
  'latitude': -8.2627,
  'longitude': -42.1545,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CEAB2',
  'nome': 'Conj. Abaiara 230 kV',
  'fonte': 'Solar',
  'potencia_mw': 163.701,
  'submercado': 'NE',
  'latitude': -7.391467,
  'longitude': -38.970836,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PIRG3',
  'nome': 'Conj. Ribeiro Gonçalves',
  'fonte': 'Solar',
  'potencia_mw': 223.212,
  'submercado': 'NE',
  'latitude': -7.6532244,
  'longitude': -45.190727,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CEPTN',
  'nome': 'Conj. Banabuiú',
  'fonte': 'Solar',
  'potencia_mw': 230.0,
  'submercado': 'NE',
  'latitude': -5.3231,
  'longitude': -38.83,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BATBV',
  'nome': 'Conj. Ituverava',
  'fonte': 'Solar',
  'potencia_mw': 196.0,
  'submercado': 'NE',
  'latitude': -12.58370142726049,
  'longitude': -44.10773300530151,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PBLZA',
  'nome': 'Conj. Luzia',
  'fonte': 'Solar',
  'potencia_mw': 117.888,
  'submercado': 'NE',
  'latitude': -6.840796,
  'longitude': -36.93287,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BAJZS2',
  'nome': 'Conj. Juazeiro Solar 2',
  'fonte': 'Solar',
  'potencia_mw': 157.068,
  'submercado': 'NE',
  'latitude': -9.5333,
  'longitude': -40.489,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PEBRI',
  'nome': 'Conj. Brígida',
  'fonte': 'Solar',
  'potencia_mw': 163.0,
  'submercado': 'NE',
  'latitude': -8.565919,
  'longitude': -39.591642,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CECAL',
  'nome': 'Conj. Calcário',
  'fonte': 'Solar',
  'potencia_mw': 132.0,
  'submercado': 'NE',
  'latitude': -5.0347,
  'longitude': -37.785,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CEFSEM',
  'nome': 'Conj. Serra do Mato',
  'fonte': 'Solar',
  'potencia_mw': 101.49,
  'submercado': 'NE',
  'latitude': -3.302,
  'longitude': -39.349,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CEMTD',
  'nome': 'Conj. Mauriti',
  'fonte': 'Solar',
  'potencia_mw': 343.768,
  'submercado': 'NE',
  'latitude': -7.366,
  'longitude': -38.781,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BAJZS',
  'nome': 'Conj. Juazeiro Solar',
  'fonte': 'Solar',
  'potencia_mw': 120.0,
  'submercado': 'NE',
  'latitude': -9.5333,
  'longitude': -40.489,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PISGO',
  'nome': 'Conj. São Gonçalo',
  'fonte': 'Solar',
  'potencia_mw': 0.0,
  'submercado': 'NE',
  'latitude': -10.103855,
  'longitude': -45.282352,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PI5FRGV',
  'nome': 'Conj. Ribeiro Gonçalves 500 kV',
  'fonte': 'Solar',
  'potencia_mw': 299.97,
  'submercado': 'NE',
  'latitude': -7.623814,
  'longitude': -45.207411,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CESDF',
  'nome': 'Conj. Sol do Futuro',
  'fonte': 'Solar',
  'potencia_mw': 81.0,
  'submercado': 'NE',
  'latitude': -3.9781,
  'longitude': -38.3939,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BAHZT',
  'nome': 'Conj. Horizonte',
  'fonte': 'Solar',
  'potencia_mw': 79.8,
  'submercado': 'NE',
  'latitude': -12.604269,
  'longitude': -44.083244,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BASSB',
  'nome': 'Conj. Sertão Solar Barreiras',
  'fonte': 'Solar',
  'potencia_mw': 94.64,
  'submercado': 'NE',
  'latitude': -12.051321,
  'longitude': -45.59781,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BA4FJZD',
  'nome': 'Conj. Juazeiro II 230 kV',
  'fonte': 'Solar',
  'potencia_mw': 277.068,
  'submercado': 'NE',
  'latitude': -9.5333,
  'longitude': -40.489,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_RNSPC',
  'nome': 'Conj. Simplice',
  'fonte': 'Solar',
  'potencia_mw': 117.54,
  'submercado': 'NE',
  'latitude': -5.8171,
  'longitude': -36.6406,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_RNFLO',
  'nome': 'Conj. Floresta',
  'fonte': 'Solar',
  'potencia_mw': 86.0,
  'submercado': 'NE',
  'latitude': -4.963689,
  'longitude': -36.916961,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PESPP',
  'nome': 'Conj. Bom Nome',
  'fonte': 'Solar',
  'potencia_mw': 83.91352,
  'submercado': 'NE',
  'latitude': -7.8725076,
  'longitude': -37.9791102,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_CELINS',
  'nome': 'Conj. Lins',
  'fonte': 'Solar',
  'potencia_mw': 182.00076,
  'submercado': 'NE',
  'latitude': -3.630218,
  'longitude': -38.922755,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BALAP',
  'nome': 'Conj. Lapa',
  'fonte': 'Solar',
  'potencia_mw': 60.0,
  'submercado': 'NE',
  'latitude': -13.310839,
  'longitude': -43.351581,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BABJU',
  'nome': 'Conj. Bom Jesus',
  'fonte': 'Solar',
  'potencia_mw': 60.0,
  'submercado': 'NE',
  'latitude': -13.299456,
  'longitude': -43.33305,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BASPD',
  'nome': 'Conj. São Pedro',
  'fonte': 'Solar',
  'potencia_mw': 54.0,
  'submercado': 'NE',
  'latitude': -13.3164,
  'longitude': -43.2728,
  'garantia_fisica_mwm': None},
 {'usina_id': 'RNFVAE',
  'nome': 'Assú V',
  'fonte': 'Solar',
  'potencia_mw': 34.0,
  'submercado': 'NE',
  'latitude': -5.54600429,
  'longitude': -37.02639026,
  'garantia_fisica_mwm': None},
 {'usina_id': 'PISDP1',
  'nome': 'Sol do Piauí',
  'fonte': 'Solar',
  'potencia_mw': 48.1,
  'submercado': 'NE',
  'latitude': -8.01500833,
  'longitude': -40.61032777,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BABJL',
  'nome': 'Conj. BJL',
  'fonte': 'Solar',
  'potencia_mw': 40.0,
  'submercado': 'NE',
  'latitude': -13.316116,
  'longitude': -43.46364,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CEUPTM',
  'nome': 'Pitombeira',
  'fonte': 'Solar',
  'potencia_mw': 47.25,
  'submercado': 'NE',
  'latitude': -4.60098333,
  'longitude': -37.64212222,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BASSDB',
  'nome': 'Conj. Serra da Babilônia',
  'fonte': 'Solar',
  'potencia_mw': 123.00086,
  'submercado': 'NE',
  'latitude': -11.1046611,
  'longitude': -41.32873333,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PISGOA',
  'nome': 'Conj. São Gonçalo A',
  'fonte': 'Solar',
  'potencia_mw': 0.0,
  'submercado': 'NE',
  'latitude': -10.103855,
  'longitude': -45.282352,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_PEMRRC',
  'nome': 'Conj. Serrita',
  'fonte': 'Solar',
  'potencia_mw': 60.0,
  'submercado': 'NE',
  'latitude': -8.025902,
  'longitude': -39.319785,
  'garantia_fisica_mwm': None},
 {'usina_id': 'CJU_BA3FIRE',
  'nome': 'Conj. Irecê 138 kV',
  'fonte': 'Solar',
  'potencia_mw': 133.4006,
  'submercado': 'NE',
  'latitude': -11.30863924018409,
  'longitude': -41.80786043713334,
  'garantia_fisica_mwm': None})

_TOP_50_SET = {uid.upper() for uid in TOP_50_USINA_IDS}
_TOP_50_ORDER = {uid.upper(): idx for idx, uid in enumerate(TOP_50_USINA_IDS)}

def normalize_usina_id(usina_id: str | None) -> str:
    return str(usina_id or "").strip().upper()

def is_top_50_usina(usina_id: str | None) -> bool:
    return normalize_usina_id(usina_id) in _TOP_50_SET

def filter_top_50_usinas(usinas: list[dict]) -> list[dict]:
    filtered = [u for u in usinas if is_top_50_usina(str(u.get("usina_id", "")))]
    return sorted(filtered, key=lambda u: _TOP_50_ORDER.get(normalize_usina_id(str(u.get("usina_id", ""))), 9999))

def list_top_50_usinas() -> list[dict]:
    return [dict(row) for row in TOP_50_USINA_ROWS]
